name: nodejs

on:
  push:
    branches: [ main, master ]
    paths:
      - 'nodejs/**'
      - '.github/workflows/nodejs.yml'
  workflow_dispatch:

concurrency:
  group: nodejs-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        node-version: [25, 24, 23, 22, 21, 20, 19, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Dockerfile exists
        run: |
          if [ ! -f "nodejs/${{ matrix.node-version }}/Dockerfile" ]; then
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nodejs/${{ matrix.node-version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/siputzx/panel:node_${{ matrix.node-version }}
          cache-from: type=gha,scope=nodejs${{ matrix.node-version }}
          cache-to: type=gha,mode=max,scope=nodejs${{ matrix.node-version }}
          provenance: false
          sbom: false
